language = "C"
no_includes = false

[export]
prefix = "app_"
renaming_overrides_prefixing = true
item_types = ["enums", "structs", "opaque", "functions", "typedefs"]
exclude = ["rust_eh_personality", "_Unwind_Resume"]
include = ["FooCallback"]

[export.rename]
FooCallback = "foo_callback"

[export.mangle]
rename_types = "SnakeCase"
