language = "C"
cpp_compat = false
pragma_once = true
no_includes = false
header = """
/*
Fix implicit declaration of function ‘usleep’:
#define _XOPEN_SOURCE 500
*/
"""
after_includes = ""
sys_includes = ["string.h", "pthread.h", "unistd.h", "sched.h"]

[export]
renaming_overrides_prefixing = true
item_types = [
  "globals",
  "constants",
  "enums",
  "structs",
  "unions",
  "opaque",
  "functions",
  "typedefs",
]
exclude = ["rust_eh_personality", "_Unwind_Resume"]
include = ["FooCallback"]

[export.rename]
FooCallback = "foo_callback"

[export.mangle]
rename_types = "SnakeCase"
