[install]
root = "."

[term]
quiet = false
verbose = false
progress.when = 'auto'

[build]
rustc-wrapper = "sccache"
# Uncomment if you want to compile static binary
#target = "x86_64-unknown-linux-musl"
rustflags = [
  #"-Cprefer-dynamic",
  "-Ctarget-cpu=native",
  "-Clink-arg=-fuse-ld=lld",
  "-Clink-args=-lc",
  "-Clink-args=-Wl,-rpath,$ORIGIN,-rpath,$ORIGIN/lib,-rpath,$ORIGIN/../lib",
  "-Cpanic=abort",
  "--verbose",
]

[target.x86_64-unknown-linux-musl]
rustflags = [
  "-Clink-args=-lc",
  "-Clinker-plugin-lto",
  "-Ctarget-feature=+crt-static",
  "-Clink-arg=-fuse-ld=lld",
  "-Crelocation-model=static",
  "-Cpanic=abort",
]
