/* automatically generated by rust-bindgen 0.71.1 */

pub type ini_handler = ::core::option::Option<
    unsafe extern "C" fn(
        user: *mut ::core::ffi::c_void,
        section: *const ::core::ffi::c_char,
        name: *const ::core::ffi::c_char,
        value: *const ::core::ffi::c_char
    ) -> ::core::ffi::c_int
>;
pub type ini_reader = ::core::option::Option<
    unsafe extern "C" fn(
        str_: *mut ::core::ffi::c_char,
        num: ::core::ffi::c_int,
        stream: *mut ::core::ffi::c_void
    ) -> *mut ::core::ffi::c_char
>;
unsafe extern "C" {
    pub fn ini_parse(
        filename: *const ::core::ffi::c_char,
        handler: ini_handler,
        user: *mut ::core::ffi::c_void
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn ini_parse_stream(
        reader: ini_reader,
        stream: *mut ::core::ffi::c_void,
        handler: ini_handler,
        user: *mut ::core::ffi::c_void
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn ini_parse_string(
        string: *const ::core::ffi::c_char,
        handler: ini_handler,
        user: *mut ::core::ffi::c_void
    ) -> ::core::ffi::c_int;
}
